version: '3.7'
services:
  web:
    build: ./.
    ports: 
      - "9000:8000"
    restart: unless-stopped
    container_name: nodejs
    env_file: ./.env
    networks: 
      - nodejs

networks:
  nodejs:
    
